version: '3.7'

services:
  mysql:
    image: bitnami/mysql:latest
    ports: 
      - 3306:3306 
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=skyrim7
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=skyrim7